apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-api
  namespace: dotnet-lab
data:
  APP_MESSAGE: "Hello from AKS"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-api
  namespace: dotnet-lab
spec:
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: lab-api
  template:
    metadata:
      labels:
        app: lab-api
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1654
        runAsGroup: 1654
        fsGroup: 1654
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: lab-api
      containers:
        - name: api
          image: __IMAGE__
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: lab-api
          env:
            - name: APP_VERSION
              value: "__VERSION__"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: temp
              mountPath: /tmp
      volumes:
        - name: temp
          emptyDir:
            sizeLimit: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: lab-api
  namespace: dotnet-lab
spec:
  type: ClusterIP
  selector:
    app: lab-api
  ports:
    - port: 80
      targetPort: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lab-api
  namespace: dotnet-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lab-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lab-api
  namespace: dotnet-lab
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: lab-api
